[package]
name = "mano"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
rexpect = "0.6.2"
tempfile = "3.23.0"

[dependencies]
rustyline = "17.0.2"
thiserror = "2.0.17"
