[package]
name = "mano"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
tempfile = "3.23.0"

[dependencies]
phf = { version = "0.13.1", features = ["macros"] }
thiserror = "2.0.17"
unicode-properties = "0.1.4"
